---
version: "3.1"
services:
  redis:
    image: redis:4.0.8
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
      - ./settings/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  mysql:
    image: mysql:5.6.39
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./settings/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
